In [1]:
import numpy as np
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
!nvidia-smi

Wed Jun 16 23:46:31 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 441.87       Driver Version: 441.87       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2060   WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   49C    P8     4W /  N/A |    164MiB /  6144MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [4]:
some_data = [[1, 2], [3, 4]]
some_data

[[1, 2], [3, 4]]

In [5]:
type(some_data)

list

In [6]:
np.array(some_data)

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(some_data)

array([[1, 2],
       [3, 4]])

In [8]:
torch.tensor(some_data)

tensor([[1, 2],
        [3, 4]])

In [9]:
some_tensor = torch.tensor(some_data)
some_tensor

tensor([[1, 2],
        [3, 4]])

In [10]:
type(some_tensor)

torch.Tensor

In [11]:
some_tensor.dtype

torch.int64

In [12]:
np_arr = np.random.rand(3, 4)
np_arr

array([[0.9931772 , 0.89678332, 0.1818014 , 0.03409466],
       [0.18339485, 0.67802089, 0.08560888, 0.37804624],
       [0.87673243, 0.99985222, 0.28521119, 0.68361965]])

In [13]:
torch.tensor(np_arr)

tensor([[0.9932, 0.8968, 0.1818, 0.0341],
        [0.1834, 0.6780, 0.0856, 0.3780],
        [0.8767, 0.9999, 0.2852, 0.6836]], dtype=torch.float64)

In [14]:
torch.from_numpy(np_arr)

tensor([[0.9932, 0.8968, 0.1818, 0.0341],
        [0.1834, 0.6780, 0.0856, 0.3780],
        [0.8767, 0.9999, 0.2852, 0.6836]], dtype=torch.float64)

In [15]:
torch.ones(3, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
my_tensor = torch.rand(3, 4)
my_tensor

tensor([[0.1414, 0.6067, 0.2778, 0.4528],
        [0.7758, 0.3974, 0.7343, 0.1836],
        [0.8198, 0.0553, 0.3536, 0.0691]])

In [19]:
my_tensor.dtype

torch.float32

In [20]:
my_tensor.device

device(type='cpu')

In [21]:
my_tensor.to("cuda")

tensor([[0.1414, 0.6067, 0.2778, 0.4528],
        [0.7758, 0.3974, 0.7343, 0.1836],
        [0.8198, 0.0553, 0.3536, 0.0691]], device='cuda:0')

In [22]:
my_tensor = my_tensor.to("cuda")

In [23]:
my_tensor.device

device(type='cuda', index=0)

In [24]:
my_tensor[:, 1:3]

tensor([[0.6067, 0.2778],
        [0.3974, 0.7343],
        [0.0553, 0.3536]], device='cuda:0')

In [25]:
my_tensor[:2, :]

tensor([[0.1414, 0.6067, 0.2778, 0.4528],
        [0.7758, 0.3974, 0.7343, 0.1836]], device='cuda:0')

In [26]:
torch.mul(my_tensor, my_tensor)

tensor([[0.0200, 0.3681, 0.0772, 0.2050],
        [0.6019, 0.1579, 0.5391, 0.0337],
        [0.6721, 0.0031, 0.1250, 0.0048]], device='cuda:0')

In [27]:
my_tensor.mul(my_tensor)

tensor([[0.0200, 0.3681, 0.0772, 0.2050],
        [0.6019, 0.1579, 0.5391, 0.0337],
        [0.6721, 0.0031, 0.1250, 0.0048]], device='cuda:0')

In [28]:
my_tensor * my_tensor

tensor([[0.0200, 0.3681, 0.0772, 0.2050],
        [0.6019, 0.1579, 0.5391, 0.0337],
        [0.6721, 0.0031, 0.1250, 0.0048]], device='cuda:0')

In [30]:
my_tensor.matmul(my_tensor.T)

tensor([[0.6703, 0.6380, 0.2790],
        [0.6380, 1.3326, 0.9303],
        [0.2790, 0.9303, 0.8050]], device='cuda:0')

In [31]:
torch.matmul(my_tensor, my_tensor.T)

tensor([[0.6703, 0.6380, 0.2790],
        [0.6380, 1.3326, 0.9303],
        [0.2790, 0.9303, 0.8050]], device='cuda:0')

In [33]:
my_tensor @ my_tensor.T

tensor([[0.6703, 0.6380, 0.2790],
        [0.6380, 1.3326, 0.9303],
        [0.2790, 0.9303, 0.8050]], device='cuda:0')

In [35]:
my_tensor.sum()

tensor(4.8676, device='cuda:0')

In [36]:
my_tensor.sum(axis=1)

tensor([1.4788, 2.0910, 1.2978], device='cuda:0')

In [37]:
my_tensor.sum(axis=0)

tensor([1.7370, 1.0594, 1.3657, 0.7055], device='cuda:0')

In [39]:
torch.cat([my_tensor, my_tensor])

tensor([[0.1414, 0.6067, 0.2778, 0.4528],
        [0.7758, 0.3974, 0.7343, 0.1836],
        [0.8198, 0.0553, 0.3536, 0.0691],
        [0.1414, 0.6067, 0.2778, 0.4528],
        [0.7758, 0.3974, 0.7343, 0.1836],
        [0.8198, 0.0553, 0.3536, 0.0691]], device='cuda:0')

In [42]:
torch.cat([my_tensor, my_tensor], axis=1)

tensor([[0.1414, 0.6067, 0.2778, 0.4528, 0.1414, 0.6067, 0.2778, 0.4528],
        [0.7758, 0.3974, 0.7343, 0.1836, 0.7758, 0.3974, 0.7343, 0.1836],
        [0.8198, 0.0553, 0.3536, 0.0691, 0.8198, 0.0553, 0.3536, 0.0691]],
       device='cuda:0')

In [58]:
torch.nn.functional.softmax(my_tensor, dim=0)#.sum(axis=0)

tensor([[0.2059, 0.4189, 0.2734, 0.4089],
        [0.3883, 0.3398, 0.4316, 0.3124],
        [0.4058, 0.2413, 0.2950, 0.2786]], device='cuda:0')

In [57]:
torch.nn.functional.softmax(my_tensor, dim=1)#.sum(axis=1)

tensor([[0.1959, 0.3120, 0.2246, 0.2675],
        [0.3128, 0.2142, 0.3000, 0.1730],
        [0.3899, 0.1815, 0.2446, 0.1840]], device='cuda:0')

In [51]:
torch.nn.functional.sigmoid(my_tensor)

tensor([[0.5353, 0.6472, 0.5690, 0.6113],
        [0.6848, 0.5981, 0.6757, 0.5458],
        [0.6942, 0.5138, 0.5875, 0.5173]], device='cuda:0')

In [59]:
my_tensor.shape

torch.Size([3, 4])

In [66]:
my_tensor.size()

torch.Size([3, 4])

In [69]:
torch.rand(10, 3, 128, 128) # batch size, channels, height, width

tensor([[[[0.7153, 0.1806, 0.2545,  ..., 0.9147, 0.4109, 0.3645],
          [0.0233, 0.9103, 0.5606,  ..., 0.5543, 0.5383, 0.8472],
          [0.5662, 0.2433, 0.7745,  ..., 0.5247, 0.8877, 0.3280],
          ...,
          [0.5694, 0.6870, 0.2550,  ..., 0.4036, 0.8572, 0.6935],
          [0.3883, 0.4528, 0.1327,  ..., 0.1261, 0.9362, 0.1621],
          [0.0271, 0.5181, 0.6185,  ..., 0.2526, 0.5853, 0.9561]],

         [[0.3816, 0.1438, 0.3386,  ..., 0.4451, 0.9350, 0.6513],
          [0.3096, 0.1589, 0.6874,  ..., 0.3346, 0.4097, 0.5132],
          [0.1743, 0.7879, 0.9424,  ..., 0.7643, 0.3003, 0.3270],
          ...,
          [0.0341, 0.3620, 0.0166,  ..., 0.9868, 0.3813, 0.8505],
          [0.6235, 0.1258, 0.3923,  ..., 0.9065, 0.9590, 0.5659],
          [0.8877, 0.6103, 0.9884,  ..., 0.8395, 0.6602, 0.5031]],

         [[0.5594, 0.2838, 0.2791,  ..., 0.1710, 0.5479, 0.4069],
          [0.9017, 0.7654, 0.2953,  ..., 0.7637, 0.2024, 0.5793],
          [0.5981, 0.6830, 0.4888,  ..., 0

In [70]:
torch.rand(10, 3, 128, 128).size()

torch.Size([10, 3, 128, 128])

In [71]:
my_tensor

tensor([[0.1414, 0.6067, 0.2778, 0.4528],
        [0.7758, 0.3974, 0.7343, 0.1836],
        [0.8198, 0.0553, 0.3536, 0.0691]], device='cuda:0')

In [72]:
my_tensor.clip(.2, .8)

tensor([[0.2000, 0.6067, 0.2778, 0.4528],
        [0.7758, 0.3974, 0.7343, 0.2000],
        [0.8000, 0.2000, 0.3536, 0.2000]], device='cuda:0')

In [74]:
my_tensor.clamp(0.2, 0.8)

tensor([[0.2000, 0.6067, 0.2778, 0.4528],
        [0.7758, 0.3974, 0.7343, 0.2000],
        [0.8000, 0.2000, 0.3536, 0.2000]], device='cuda:0')

In [79]:
my_tensor.cpu().detach().numpy()

array([[0.14141071, 0.6066982 , 0.27784956, 0.45279944],
       [0.7758069 , 0.39742166, 0.7342501 , 0.18356568],
       [0.8198322 , 0.05526632, 0.35361207, 0.06910187]], dtype=float32)

In [82]:
torch.empty(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])