### Containers
* Module
* Sequential
* ModuleList
* ModuleDict

### Layers
* Conv1d
* Conv2d
* MaxPool1d
* MaxPool2d
* AvgPool1d
* AvgPool2d
* BatchNorm1d
* BatchNorm2d
* LayerNorm
* LSTM
* GRU
* Linear
* Dropout
* Embedding
* Transformer

### Activations
* ReLU
* LeakyReLU
* Sigmoid
* Tanh
* Softmax

### Loss Functions
* MSELoss
* CrossEntropyLoss
* NLLoss
* BCELoss
* BCEWithLogitsLoss

In [1]:
import numpy as np
import torch
import torch.nn as nn

In [2]:
class Model(nn.Module):
    
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(128, 32)
        self.layer2 = nn.Linear(32, 16)
        self.layer3 = nn.Linear(16, 1)
        
    def forward(self, features):
        x = self.layer1(features)
        x = self.layer2(x)
        x = self.layer3(x)
        return x

In [3]:
model = Model()

In [4]:
print(model)

Model(
  (layer1): Linear(in_features=128, out_features=32, bias=True)
  (layer2): Linear(in_features=32, out_features=16, bias=True)
  (layer3): Linear(in_features=16, out_features=1, bias=True)
)


In [5]:
features = torch.rand(2, 128)

In [6]:
model(features)

tensor([[-0.0958],
        [-0.0534]], grad_fn=<AddmmBackward>)

In [7]:
features.device

device(type='cpu')

In [8]:
features = features.to("cuda")
model = Model()
model.to("cuda")
model(features)

tensor([[-0.1767],
        [-0.1441]], device='cuda:0', grad_fn=<AddmmBackward>)

In [9]:
# !nvidia-smi

In [11]:
class Model(nn.Module):
    
    def __init__(self):
        super().__init__()
        self.base = nn.Sequential(
            nn.Linear(128, 32),
            nn.Linear(32, 16),
            nn.Linear(16, 1),
        )
        
    def forward(self, features):
        x = self.base(features)
        return x

In [12]:
features = features.to("cuda")
model = Model()
model.to("cuda")
model(features)

tensor([[-0.5304],
        [-0.5787]], device='cuda:0', grad_fn=<AddmmBackward>)