#### Autograd

In [1]:
import torch

In [2]:
a = torch.tensor([5.], requires_grad=True)
b = torch.tensor([6.], requires_grad=True)

In [3]:
a

tensor([5.], requires_grad=True)

In [4]:
b

tensor([6.], requires_grad=True)

In [5]:
y = a**3 - b**2
y

tensor([89.], grad_fn=<SubBackward0>)

\begin{equation}
    y = a^3 - b^2
\end{equation}

Partial deri

\begin{equation}
    \frac{\delta y}{\delta a} = 3a^2
\end{equation}

\begin{equation}
    \frac{\delta y}{\delta b} = -2b
\end{equation}

In [6]:
a.grad, b.grad

(None, None)

In [7]:
y.backward()

In [8]:
a.grad, b.grad

(tensor([75.]), tensor([-12.]))

In [23]:
W = torch.randn(10, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

In [24]:
W

tensor([[-0.5471],
        [-0.3135],
        [ 0.8502],
        [-0.9551],
        [-0.9050],
        [ 0.5253],
        [ 0.8984],
        [ 0.4641],
        [ 0.3400],
        [ 0.4128]], requires_grad=True)

In [25]:
b

tensor([-0.0159], requires_grad=True)

In [26]:
x = torch.rand(1, 10)

In [27]:
x

tensor([[0.2044, 0.7568, 0.9861, 0.2476, 0.7612, 0.5601, 0.5545, 0.2210, 0.8436,
         0.0341]])

In [28]:
output = torch.matmul(x, W) + b

In [29]:
output

tensor([[0.7440]], grad_fn=<AddBackward0>)

In [30]:
loss = 1 - output
loss

tensor([[0.2560]], grad_fn=<RsubBackward1>)

In [31]:
loss.backward()

In [32]:
W.grad

tensor([[-0.2044],
        [-0.7568],
        [-0.9861],
        [-0.2476],
        [-0.7612],
        [-0.5601],
        [-0.5545],
        [-0.2210],
        [-0.8436],
        [-0.0341]])

In [33]:
b.grad

tensor([-1.])

\begin{equation}
w -= lr * \bar{w}
\end{equation}

In [34]:
with torch.no_grad():
    W = W - 0.01 * W.grad.data

In [35]:
W

tensor([[-0.5450],
        [-0.3059],
        [ 0.8601],
        [-0.9526],
        [-0.8974],
        [ 0.5309],
        [ 0.9039],
        [ 0.4663],
        [ 0.3485],
        [ 0.4132]])